/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import static forms.GanttChart.getFriendlyTime;
import static forms.databaseHelper.executeUpdate;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import startofagreatfuture.Artisan;
import startofagreatfuture.HTMLSelectedHelper;
import startofagreatfuture.JDBCUtil;
import startofagreatfuture.Job;

/**
 *
 * @author bheki
 */
public class SelectArtisan extends HomeScreen {
    private DefaultMutableTreeNode td;
    List<String> myArtisanList= new ArrayList<>();
    int JCN;
    Artisan pe ;

    /**
     * Creates new form SelectArtisan
     * @param JCN
     */
    public SelectArtisan(int JCN) {
        super(0);
            pe = new Artisan();
            this.JCN =JCN;
            initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        selectArtisansButton = new javax.swing.JButton();
        cancelSelectingButton = new javax.swing.JButton();
        editArtisanAttributesButton = new javax.swing.JButton();
        newArtisanButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree(pe.getArtisanTree());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(600, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        selectArtisansButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArtisansButton.setText("Select Artisans");
        selectArtisansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArtisansButtonActionPerformed(evt);
            }
        });

        cancelSelectingButton.setText("Cancel");
        cancelSelectingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSelectingButtonActionPerformed(evt);
            }
        });

        editArtisanAttributesButton.setText("Edit Attributes");
        editArtisanAttributesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editArtisanAttributesButtonActionPerformed(evt);
            }
        });

        newArtisanButton.setText("New Artisan");
        newArtisanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newArtisanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newArtisanButton)
                    .addComponent(selectArtisansButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelSelectingButton)
                    .addComponent(editArtisanAttributesButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelSelectingButton, editArtisanAttributesButton, newArtisanButton, selectArtisansButton});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newArtisanButton)
                    .addComponent(editArtisanAttributesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectArtisansButton)
                    .addComponent(cancelSelectingButton))
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Attribute", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jScrollPane2.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectArtisansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArtisansButtonActionPerformed
        // TODO add your handling code here:
        
        if (!jTree1.isSelectionEmpty()) 
        {
            Connection conn =JDBCUtil.getConnection();
            TreePath[] ooo = jTree1.getSelectionModel().getSelectionPaths();
            for (TreePath mine : ooo) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) mine.getLastPathComponent();
                System.out.println("node "+node);
                Object myObject = node.getUserObject();
                Artisan myArtisan = (Artisan)myObject;
                myArtisanList.add(myArtisan.getSRNumber());
            }
            String firstArtisan = myArtisanList.get(0);
            try {
                System.out.println("myArtisanList"+myArtisanList);
                new Job().setWorkers(myArtisanList, JCN,conn);
                StringBuilder query = new StringBuilder("UPDATE artisan SET status = 'u' WHERE SRNumber = '"+myArtisanList.get(0)+"'");
                myArtisanList.remove(0);
                String hmt = HomeScreen.htmlSelected;
                HTMLSelectedHelper help = new HTMLSelectedHelper(hmt);
                String eqID=help.getEquipmentID();
                String updateLastSeen = "UPDATE`"+eqID+"` SET value =? where property = 'Last Worked on'";
                String updatePerson="UPDATE `"+eqID+"`SET value =(SELECT name FROM artisan WHERE srNumber="+firstArtisan+") where property = 'By'";
                
                
                for(String SRNumber: myArtisanList)
                {
                    query = query.append("OR SRNumber =?");
                }
                String qs = query.toString();
                PreparedStatement pstmt = conn.prepareStatement(qs);
                PreparedStatement pstmt1 = conn.prepareStatement(updateLastSeen);
                PreparedStatement pstmt2 = conn.prepareStatement(updatePerson);
                        
                for(int index = 1;index< myArtisanList.size()+1;index++)
                {
                    pstmt.setString(index, myArtisanList.get(index-1));
                }
                
                pstmt1.setString(1, getFriendlyTime(LocalDateTime.now()));
                System.out.println("prepared statement for entering arisans:\n"+pstmt);
                System.out.println("prepared statement for updating last seen:\n"+pstmt1);
                System.out.println("prepared statement for updating person:\n"+pstmt2);
                
                executeUpdate(pstmt,conn);
                executeUpdate(pstmt1,conn);
                executeUpdate(pstmt2,conn);
            } catch (SQLException ex) 
            {
                JDBCUtil.rollback(conn);
                ex.printStackTrace();
            }
            finally{JDBCUtil.closeConnection(conn);}

            this.dispose();
        }
        
    }//GEN-LAST:event_selectArtisansButtonActionPerformed

    private void cancelSelectingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSelectingButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelSelectingButtonActionPerformed

    private void newArtisanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newArtisanButtonActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode node=(DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
        Artisan selection =(Artisan)node.getUserObject();
        
        
    }//GEN-LAST:event_newArtisanButtonActionPerformed

    private void editArtisanAttributesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editArtisanAttributesButtonActionPerformed
        // TODO add your handling code here:
        JTree jTree2 = new JTree(td);
        jScrollPane2.setViewportView(jTree2);
        
    }//GEN-LAST:event_editArtisanAttributesButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelSelectingButton;
    private javax.swing.JButton editArtisanAttributesButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton newArtisanButton;
    private javax.swing.JButton selectArtisansButton;
    // End of variables declaration//GEN-END:variables
}
